// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./../renderer/components/Aside.vue')['default']
    Contextmenu: typeof import('./../renderer/components/Contextmenu.vue')['default']
    Detail: typeof import('./../renderer/components/Detail.vue')['default']
    Footer: typeof import('./../renderer/components/Footer.vue')['default']
    Frame: typeof import('./../renderer/components/Frame.vue')['default']
    List: typeof import('./../renderer/components/List.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    Share: typeof import('./../renderer/components/Share.vue')['default']
    Waterfall: typeof import('./../renderer/components/Waterfall.vue')['default']
  }
}

export { }
