name: release-build

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install and Build
        run: |
          npm i
          npx vite build
          npx electron-builder -p always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}